### ISSUE TITLE
AttributeError: module 'taichi' has no attribute 'ti_core'

### ISSUE THREAD

**Issue by matyklug18** [taichi-dev/taichi_elements#52]
```
Creating simulation of res 64, size 10.0
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/home/matyk/Desktop/functionalblendrik/functions-blender-2.83-cd5f9516db8e-linux64/2.83/python/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/home/matyk/Desktop/functionalblendrik/functions-blender-2.83-cd5f9516db8e-linux64/2.83/python/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/matyk/.config/blender/2.83/scripts/addons/taichi_elements/operators.py", line 243, in init_sim
    solv = mpm_solver.MPMSolver((res, res, res), size=size)
  File "/home/matyk/.config/blender/2.83/scripts/addons/taichi_elements/engine/mpm_solver.py", line 100, in __init__
    self.set_gravity((0, -9.8, 0))
  File "/home/matyk/.config/blender/2.83/scripts/addons/taichi_elements/engine/mpm_solver.py", line 110, in set_gravity
    self.gravity[None] = g
  File "/home/matyk/Desktop/functionalblendrik/functions-blender-2.83-cd5f9516db8e-linux64/2.83/python/lib/python3.7/site-packages/taichi/lang/matrix.py", line 312, in __setitem__
    self(i, j)[index] = item[i][j]
  File "/home/matyk/Desktop/functionalblendrik/functions-blender-2.83-cd5f9516db8e-linux64/2.83/python/lib/python3.7/site-packages/taichi/lang/expr.py", line 175, in __setitem__
    self.materialize_layout_callback()
  File "/home/matyk/Desktop/functionalblendrik/functions-blender-2.83-cd5f9516db8e-linux64/2.83/python/lib/python3.7/site-packages/taichi/lang/impl.py", line 180, in materialize
    ti.trace("Materializing layout...".format())
  File "/home/matyk/Desktop/functionalblendrik/functions-blender-2.83-cd5f9516db8e-linux64/2.83/python/lib/python3.7/site-packages/taichi/misc/util.py", line 138, in logger
    if taichi.ti_core.logging_effective(name):
AttributeError: module 'taichi' has no attribute 'ti_core'
```
ubuntu, 19.10, no cuda installed, kernel  5.3.0-51-generic, python 3.7

this: 
```py
import taichi
taichi.ti_core
```
works just fine, however, inside the scripting console.

**Comment by PavelBlend** [comment]
What version of taichi did you install? At the moment, the addon was tested on version 0.5.11. Try to remove taichi if it has a version higher than 0.5.11. And reinstall with this command:
`pip install taichi==0.5.11`

**Comment by matyklug18** [comment]
seems like that worked, thanks!
