### ISSUE TITLE
Does this work in windows?

### ISSUE THREAD

**Issue by steven850** [taichi-dev/taichi_elements#58]
Hi, this elements work with blender in windows or is this linux only?

**Comment by bestman8** [comment]
it works for me and i have windows 
it isn't easy to install

**Comment by steven850** [comment]
Well I followed the steps in the readme which where useless to be honest. Manually installed everything, but when I go to enable the addon in blender, blender crashes to desktop. Using 2.83.5 LTS

**Comment by archibate** [comment]
Could you run blender in console (`cmd`) and attach the output here? Related issue: https://github.com/taichi-dev/taichi_elements/issues/54#issuecomment-645771417.

**Comment by steven850** [comment]
Settings loaded
The custom limb directory seems invalid: C:\Custom Limbs/
BlendLuxCore 2.4 registered (with pyluxcore 2.4)
Load Handler:
Updating device list
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Program Files\\Blender Foundation\\Blender 2.83\\2.83\\scripts\\addons\\_distutils_hack\\__init__.py'
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Program Files\\Blender Foundation\\Blender 2.83\\2.83\\scripts\\addons\\astor\\__init__.py'
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Program Files\\Blender Foundation\\Blender 2.83\\2.83\\scripts\\addons\\colorama\\__init__.py'
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Program Files\\Blender Foundation\\Blender 2.83\\2.83\\scripts\\addons\\dill\\__init__.py'
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Program Files\\Blender Foundation\\Blender 2.83\\2.83\\scripts\\addons\\easy_install.py'
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Program Files\\Blender Foundation\\Blender 2.83\\2.83\\scripts\\addons\\numpy\\__init__.py'
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Program Files\\Blender Foundation\\Blender 2.83\\2.83\\scripts\\addons\\pkg_resources\\__init__.py'
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Program Files\\Blender Foundation\\Blender 2.83\\2.83\\scripts\\addons\\pybind11\\__init__.py'
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Program Files\\Blender Foundation\\Blender 2.83\\2.83\\scripts\\addons\\setuptools\\__init__.py'
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Program Files\\Blender Foundation\\Blender 2.83\\2.83\\scripts\\addons\\sourceinspect\\__init__.py'
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Program Files\\Blender Foundation\\Blender 2.83\\2.83\\scripts\\addons\\taichi\\__init__.py'
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Users\\TR\\AppData\\Roaming\\Blender Foundation\\Blender\\2.83\\scripts\\addons\\addon.py'
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Users\\TR\\AppData\\Roaming\\Blender Foundation\\Blender\\2.83\\scripts\\addons\\install_blender_addon.py'
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Users\\TR\\AppData\\Roaming\\Blender Foundation\\Blender\\2.83\\scripts\\addons\\setup.py'
[Taichi] mode=release
Fatal Python error: take_gil: NULL tstate


C:\Program Files\Blender Foundation\Blender 2.83>

**Comment by archibate** [comment]
> C:\Program Files\Blender Foundation\Blender 2.83\2.83\scripts\addons\taichi\init.py'

The install location seems make Blender consider `taichi` as a plugin while it's not..

Does http://github.com/taichi-dev/taichi_blend, which does not require `pip` for installing `taichi` work for you?

**Comment by steven850** [comment]
that seem to work

 import taichi as ti
[Taichi] mode=release
[Taichi] version 0.6.31, llvm 10.0.0, commit 1d4c083c, win, python 3.7.4

**Comment by steven850** [comment]
Cant load the examples 



Traceback (most recent call last):
  File "\balls.py", line 2, in <module>
ModuleNotFoundError: No module named 'taichi_glsl'
Error: Python script failed, check the message in the system console

Traceback (most recent call last):
  File "\break_cloth.py", line 1, in <module>
ModuleNotFoundError: No module named 'reblend'
Error: Python script failed, check the message in the system console

**Comment by archibate** [comment]
> Cant load the examples
> 
> Traceback (most recent call last):
> File "\balls.py", line 2, in
> ModuleNotFoundError: No module named 'taichi_glsl'
> Error: Python script failed, check the message in the system console
> 
> Traceback (most recent call last):
> File "\break_cloth.py", line 1, in
> ModuleNotFoundError: No module named 'reblend'
> Error: Python script failed, check the message in the system console

Sorry, I forgot to add extra dependencies like `taichi_glsl` to `Taichi-Blend.zip`.. But `mpm3d.py` should work?

**Comment by steven850** [comment]
mpm3d loads a point cloud into the 3d viewport. Can play it but cant make any other changes. Im assuming thats correct?

**Comment by archibate** [comment]
Yes, if you press the Space button to start animation, the point cloud will move like liquid. Otherwise it will raise some error in console.

**Comment by steven850** [comment]
Yes it does. I also downloaded 2 of the demo blend files. They dont seem to work properly, 2 of the nodes show as undefined. Is this because of the missing glsl or have the demo blend files not been updated?

**Comment by archibate** [comment]
> Yes it does.

Then we can confirm `taichi` is working well in Windows+Blender.

> I also downloaded 2 of the demo blend files. They dont seem to work properly, 2 of the nodes show as undefined. Is this because of the missing glsl or have the demo blend files not been updated?

I can't make them functional too, keep getting this error:

```
错误: Traceback (most recent call last):
  File "/usr/share/blender/2.83/scripts/startup/bl_operators/userpref.py", line 448, in execute
    mod = addon_utils.enable(self.module, default_set=True, handle_error=err_cb)
  File "/usr/share/blender/2.83/scripts/modules/addon_utils.py", line 368, in enable
    if mod.bl_info.get("blender", (0, 0, 0)) < (2, 80, 0):
AttributeError: module 'taichi_elements' has no attribute 'bl_info'

location: <unknown location>:-1
```

I run `utils/install_blender_addon.py`, and it doesn't even functional when cwd is not `utils`. The required environment variable `BLENDER_USER_ADDON_PATH` is also not found in README.
I'm wondering if we could make things less complicated? Why don't we just simply move `blender` to `taichi_elements.blender`? It's not a big disk usage for non-Blender users, compared to `taichi_core.so` which is around 50M.

**Comment by steven850** [comment]
This is the error I get in the console when opening the demo blends.

Read blend: C:\Users\TR\Desktop\blender_simple_simulation_01.blend
Load Handler: C:\Users\TR\Desktop\blender_simple_simulation_01.blend
Megascans Plugin Error initializing the thread. Error:  [WinError 10048] Only one usage of each socket address (protocol/network address/port) is normally permitted
Updating device list

and the file opens but the simulation doesnt work. See screen shot of nodes. 
![nodes](https://user-images.githubusercontent.com/43098060/92329552-603b8580-f068-11ea-82b6-8a33628e67b4.jpg)
