### ISSUE TITLE
Error enabling the addon _ "can't use starred expression here"

### ISSUE THREAD

**Issue by AnasFX** [taichi-dev/taichi_elements#80]
Blender : 2.93.4
Branch : https://github.com/PavelBlend/taichi_elements.git

Hi, when I try to enable the addon I get this error :

Traceback (most recent call last):
  File "C:\blender-2.93.4-windows-x64\2.93\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\blender-2.93.4-windows-x64\2.93\scripts\addons\taichi_elements\__init__.py", line 27, in <module>
    from . import addon
  File "C:\blender-2.93.4-windows-x64\2.93\scripts\addons\taichi_elements\addon.py", line 3, in <module>
    from . import tree, categories, nodes, sockets, operators, handlers
  File "C:\blender-2.93.4-windows-x64\2.93\scripts\addons\taichi_elements\operators.py", line 253
    (*collider.position),
     ^
SyntaxError: can't use starred expression here

Also any news about fixing for (Force Fields) nodes that doesn't show in blender Taichi_Elements Node editor, even the examples that require forces doesn't work because there are no force nodes

**Comment by PavelBlend** [comment]
@AnasFX download the latest commit from here:
https://github.com/taichi-dev/taichi_elements/tree/e6d2db2b74f5177a1bdd615d485f49ca0fcfb9d3
Click on the green button `Code` > `Download ZIP`.
I was fixing this error.
